import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import localFont from "next/font/local";
// import Header from "@/components/elements/Header";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
      <head></head>
      {/* <body> */}
      <body className={`${pretendard.variable} font-pretendard bg-stone-800 text-stone-100`}>
        {/* <Header initialDarkMode={true} /> */}
        {children}
      </body>
    </html>
  );
}
